# -*- coding: utf-8 -*-
"""calcaltor.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UBku80ARC9qSc4zEaWFI9nTDmCeMrNBk
"""

print("Welcome to the Simple Calculator!")

add = lambda x, y: x + y
subtract = lambda x, y: x - y
multiply = lambda x, y: x * y
divide = lambda x, y: x / y

while True:

    print("\n1. Addition (+)")
    print("2. Subtraction (-)")
    print("3. Multiplication (*)")
    print("4. Division (/)")
    print("5. Exit")

    choice = input("Enter your choice: ")


    if choice  not in ["1", "2", "3", "4", "5"]:
        print("Invalid choice. Please try again.")
        continue


    if choice == "5":
        print("Thank you for using the calculator!")
        break

    if choice in ["1", "2", "3", "4"]:

        num1 = float(input("Enter first number: "))
        num2 = float(input("Enter second number: "))

        if choice == "1":
            print("Result:", add(num1, num2))

        elif choice == "2":
            print("Result:", subtract(num1, num2))

        elif choice == "3":
            print("Result:", multiply(num1, num2))

        elif choice == "4":
            if num2 == 0:
                print("Cannot divide by zero!")
            else:
                print("Result:", divide(num1, num2))

        again = input("Do you want another calculation? (yes/no): ")

        if again.lower() == "no":
            print("Thank you for using the calculator!")
            break

    else:
        print("Invalid choice. Please try again.")

